name: "CI tests"
on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          echo "set man-db/auto-update false" | sudo debconf-communicate; sudo dpkg-reconfigure man-db
          sudo apt install -y zsh
      - name: Run tests
        run: |
          make test
